@echo off
cd ..
cd khms3.google.com
call delete_pictures.bat
cd ..
cd mt.google.com
call delete_pictures.bat
cd ..
cd mt1.google.com
call delete_pictures.bat
cd ..
cd mt2.google.com
call delete_pictures.bat
cd ..
cd mw1.google.com
call delete_pictures.bat
cd ..
cd server.arcgisonline.com
call delete_pictures.bat
cd ..
cd server.arcgisonline.com-1
call delete_pictures.bat
cd ..
cd server.arcgisonline.com-2
call delete_pictures.bat
cd ..
cd server.arcgisonline.com-3
call delete_pictures.bat
cd ..
cd server.arcgisonline.com-4
call delete_pictures.bat
cd ..
cd services.arcgisonline.com
call delete_pictures.bat
cd ..
cd tile.memomaps.de
call delete_pictures.bat
cd ..
